### ISSUE TITLE
about alignment

### ISSUE THREAD

**Issue by borhanMorphy** [Nicholasli1995/VisualizingNDF#1]
Hi,
congrats for the great work you done here! I want to ask about the alignment script that you used for the CACD2000 dataset. Could you please share it ? Or if you already do, where could i find it because i couldn't find one.

**Comment by Nicholasli1995** [comment]
Hi, I have uploaded the pre-processing script for CACD (cacd_process.py) to src folder. Some relevant files are placed in "../data/CACD_split".

Data pre-processing and training code for age estimation will be released and cleaned in the future.

> Hi,
> congrats for the great work you done here! I want to ask about the alignment script that you used for the CACD2000 dataset. Could you please share it ? Or if you already do, where could i find it because i couldn't find one.

**Comment by borhanMorphy** [comment]
thanks!
