### ISSUE TITLE
i want to get cacd pre-processed images

### ISSUE THREAD

**Issue by hyokhyok** [Nicholasli1995/VisualizingNDF#5]
hi nicholasli

i want to get cacd preprocessed images. 
you maybe upload this file before, but now i can't download this file

![image](https://user-images.githubusercontent.com/37270203/135033836-9ed7db6b-0a12-455b-aff1-b8a47bcb598a.png)

and in your code cacd-process.py used below file.  
/data/CACD_split/train.npy
but i can't find this file only can find 'train_cacd_processed.npy' file 
is it same file?

thank you

**Comment by nikhil031294** [comment]
Having same issue! Please help

**Comment by Nicholasli1995** [comment]
> Having same issue! Please help

It seems the old google drive file was lost. I will upload again and update the link in a week.

**Comment by Nicholasli1995** [comment]
> hi nicholasli
> 
> i want to get cacd preprocessed images. you maybe upload this file before, but now i can't download this file
> 
> ![image](https://user-images.githubusercontent.com/37270203/135033836-9ed7db6b-0a12-455b-aff1-b8a47bcb598a.png)
> 
> and in your code cacd-process.py used below file. /data/CACD_split/train.npy but i can't find this file only can find 'train_cacd_processed.npy' file is it same file?
> 
> thank you



> Having same issue! Please help

The link is updated.
